SELECT TOP (10)
    name
FROM VJSCL.sys.tables
WHERE name LIKE 'ord\_______' ESCAPE '\'
-- this is the order table
;

SELECT TOP (10)
    OH_HEADER_REF, *
FROM VJSCL.[dbo].[ORD_HEADER]
WHERE OH_ORDER_NUMBER = '767658'
-- '767658' is the order number
;

SELECT TOP (10)
    *
FROM VJSCL.[dbo].[ORD_DETAIL]
WHERE OD_ORDER_NUMBER = '767658'
-- '767658' is the order number
;

SELECT TOP (10)
    *
FROM VJSCL.dbo.SL_TRANSACTIONS
-- invoice table
WHERE ST_HEADER_REF = '651978'
-- '651978' is the transaction header reference, the invoice number
;

SELECT TOP (10)
    DET_STOCK_CODE,
    *
FROM VJSCL.dbo.SL_PL_NL_DETAIL
WHERE DET_HEADER_REF = '651978'
-- '651978' is the transaction header reference, the invoice number
-- DET_PRIMARY is the audit No.
;

-- Querying STK_STOCK to retrieve the main stock record for the given product code.
-- This table may contain the primary stock information, whereas STK_STOCK_2 could store supplementary or historical data.
SELECT TOP (10)
    *
FROM VJSCL.dbo.STK_STOCK
WHERE STKCODE = '30TMP_836945'
;

SELECT TOP (10)
    *
FROM VJSCL.dbo.STK_STOCK_2
WHERE STKCODE2 = '30TMP_836945'
-- '30TMP_836945' is the stock code, the product code
;


SELECT TOP (10)
    stk_usrchar5, -- this is the barcode
    *
FROM VJSCL.dbo.STK_STOCK3
WHERE STKCODE3 = '30TMP_836945'
-- '30TMP_836945' is the stock code, the product code
;

select CU_TABFIELD_14
from VJSCL.dbo.LANG_TABCARD
where LANGCODE_TABCARD='ENGLISH'
;

select USER_ID, USER_NAME, USER_PASSWORD, USER_MASTER, USER_STARTUP_OP, USER_START_MOD, USER_LANGUAGE, USER_ACTIVE, DATE_IN, TIME_IN, TIME_OUT, POST_TO_NEXT_CST, POST_UPTO_CST, USER_ALLOC_AC_S, USER_ALLOC_AC_P, POST_TO_NEXT_NL, POST_TO_NEXT_PL,
    POST_TO_NEXT_SL, USER_BATCHING, USER_PRINTING, POST_TO_NEXT_SOP, POST_TO_NEXT_POP, POST_TO_NEXT_STK, POST_UPTO_STK, POST_UPTO_NL, POST_UPTO_PL, POST_UPTO_SL, POST_UPTO_SOP, POST_UPTO_POP, WINDOW_POSITION, STAGGER_HEIGHT, STAGGER_WIDTH, USER_RPT, USER_OPTS_SAVED, USER_SL_FUTURE, USER_PL_FUTURE,
    USER_NL_FUTURE, USER_OPTION30, USER_STK_FUTURE, USER_SOP_FUTURE, USER_POP_FUTURE, USER_CST_FUTURE, USER_SOP_B_OP1, USER_SOP_B_OP2, USER_SOP_B_OP3, USER_SOP_B_OP4, USER_SOP_B_OP5, USER_SOP_B_OP6, USER_SOP_B_OP7, USER_SOP_B_OP8, USER_SOP_B_OP9, USER_POP_B_OP1, USER_POP_B_OP2, USER_POP_B_OP3,
    USER_POP_B_OP4, USER_POP_B_OP5, USER_POP_B_OP6, USR_PRIMARY, USER_CB_POPUPALLOC, USER_CB_TABUPDATE, USER_CB_VALUEENTRY, USER_CB_BYPASSCOST, USR_CHG_PASWD_DATE, USER_TAB_DEFAULT, USER_POP_BUDGET_LINE, USER_ORDER_BUDGET, USER_CURRENT_BUDGET, USER_PREVIOUS_BUDGET, USER_EXCEED_OTHER_NL, USER_AUTHORISE_OWN, USER_NL_BUDGET, USER_CST_BUDGET, USER_POP_BUDGET, USER_POP_SHOW_MESSAGE, USER_INVREG_APPROVER1, USER_INVREG_APPROVER2, USER_INVREG_APPROVER3, USER_INVREG_OVERIDE, USER_EM_NAME, USER_EM_MAPI_PASSWORD, USER_EM_ADDRESS, USER_EM_MAPI_PROFILE_NAME, USER_PROFILE_CODE, USER_LEVEL, USER_GROUP, USER_PASSWORD_DATE, USER_NUMBER_LOGONS, USER_PUTIN, USER_DATE_PUTIN, USER_EDITED, USER_DATE_EDITED, USER_SRV_HEADER_KEY, USER_SRV_ACTION, SYS_ACD_USERNAME, SYS_ACD_PASSWORD, SYS_ACD_SESSION, SYS_ACD_USE_DEFAULTS, USER_ENABLED_SP, USER_SERVICEPACK_PATH, USER_HTMLHELP_PATH, USER_CRYSTALREPS_PATH, USER_USER_TOOLBAR, USER_SYS_MENU_STYLE, USER_EXTERNALDOCS_PATH, USER_BUDGET_GROUP, USER_AUTHORISE_ORDERS, USER_AUTHORISE_TYPE, USER_AUTHORISE_ALL, USER_CHECK_BUDGET_VALUES, USER_FAX_USE_PRINT_DRIVER, USER_FAX_PRINT_DRIVER, USER_FAX_SOFTWARE_LINK, USER_FAX_USE_USER_SETTINGS, USER_FAX_COVERPAGE, USER_DOMAIN, USER_DESCRIPTION, USER_START_WINDOW, USER_XACTIVE, USER_CRM_ACTIVE, USER_EDI_PATH, USER_CRM_SCREEN_LAYOUT, USER_ACD_DOCUMENTS_PATH, USER_NAVIGATOR_OPTIONS, USER_SHOW_BROWSER, USER_BROWSER_URL, USER_BROWSER_OPTION, USER_DASHBOARD_PATH, USER_DMS_USERNAME, USER_DMS_PASSWORD, USER_DMS_USERID, USER_DMS_PRINT_BARCODE, USER_DMS_WIN_AUTH, USER_LOCKED, USER_WFF_ADMINISTRATOR, USER_EM_BCC_ADDRESS, USER_EM_COPY_TO_BCC, USER_EM_SMTP_USER_LINK, USER_EM_MODE, USER_ACLOUD, USER_SUB_ANALYSIS_OPTION, USER_FILE_REPORTS_PATH, USER_BACS_EXPORT_OPTION
from VJSCL.dbo.SYS_USER with (nolock)
where USER_ID = 'SA';